### ISSUE TITLE
error in help file - DSensemble - missing file?

### ISSUE THREAD

**Issue by eliotmcintire** [metno/esd#123] opened 2015-10-15 00:55 UTC
In the help file for DSensemble, there is a function call that breaks because of missing `air.2m.mon.mean.nc`:

    rcp4.5 <- DSensemble.t2m(Oslo,path='~',rcp='',pattern = "tas_Amon_",biascorrect=TRUE, area.mean.expl=TRUE, predictor = "~/air.2m.mon.mean.nc",plot=TRUE)

Downloading `air.2m.mon.mean.nc` from 
http://www.esrl.noaa.gov/psd/repository/entry/get/air.2m.mon.mean.nc?entryid=synth%3Ae570c8f9-ec09-4e89-93b4-babd5651e7a9%3AL25jZXAucmVhbmFseXNpcy5kZXJpdmVkL3N1cmZhY2VfZ2F1c3MvYWlyLjJtLm1vbi5tZWFuLm5j
 does not help. After putting all files in the ~ path, I still I get the following error:

`Error in R_nc_open: NetCDF: Unknown file format`

Using Windows 7.0, R 3.2.2, 64-bit.

**Comment by abdelkaderm** [comment] 2015-10-15 11:00
Hi, can you try `retrieve` to get the data first before using `DSensemble` and let me know if you were able to read the data from the file sth like 
```r
predictor <- retrieve(ncfile="~/air.2m.mon.mean.nc")
```
But `~` will not work on as a default path for Windows , are you using Linux from Windows ?

**Comment by eliotmcintire** [comment] 2015-10-16 18:09
The error was the same:

    Error in R_nc_open: NetCDF: Unknown file format

Using Windows 7.0, R 3.2.2, 64-bit, plus:

    > devtools::session_info()
    Session info ----------------------------------------------------
    setting  value                       
    version  R version 3.2.2 (2015-08-14)
    system   x86_64, mingw32             
    ui       RStudio (0.98.1103)         
    language (EN)                        
    collate  English_Canada.1252         
    tz       America/Los_Angeles         
    date     2015-10-16                  

    Packages --------------------------------------------------------
    package    * version   date       source                    
    devtools   * 1.9.1     2015-09-11 CRAN (R 3.2.2)            
    esd        * 1.0       2015-10-14 Github (metno/esd@0a978be)
    lattice      0.20-33   2015-07-14 CRAN (R 3.2.2)            
    memoise      0.2.1     2014-04-22 CRAN (R 3.2.0)            
    ncdf       * 1.6.8     2014-08-25 CRAN (R 3.2.2)            
    rstudio      0.98.1103 2015-09-24 local                     
    rstudioapi   0.3.1     2015-04-07 CRAN (R 3.2.0)            
    zoo        * 1.7-12    2015-03-16 CRAN (R 3.2.2)

**Comment by abdelkaderm** [comment] 2015-10-19 07:36
Hi, your file paths definition is wrong. Windows uses different way of defining paths to files as far as I know. You need to replace the `~` by the rcp45 path directory and predictor path as well. Can you send me the return value of `getwd()` from R.

Bests,

**Comment by eliotmcintire** [comment] 2015-10-20 00:02
I am not sure what you mean. The file is there (~ does work on Windows, it is just idiosyncratic, it works on my Windows system because I made it work there)... see:

    dir(path = "~", pattern="air.2m.mon.mean.nc")
    [1] "air.2m.mon.mean.nc"

Trying to run your example with the direct written path, I get the same error as using `~`:

    predictor <- retrieve(ncfile="c:/Eliot/air.2m.mon.mean.nc")
    Error in R_nc_open: NetCDF: Unknown file format
    Error in open.ncdf(ncfile) : 
    Error in open.ncdf trying to open file c:/Eliot/air.2m.mon.mean.nc 

Is there a version of the  air.2m.mon.mean.nc file that is older that works?  Perhaps the one I downloaded from the internet is not the same as the one you have?

I get a different error on my linux system:

    rcp4.5 <- DSensemble.t2m(Oslo,path='~',rcp='',pattern = "tas_Amon_",biascorrect=TRUE, area.mean.expl=TRUE, predictor = "~/air.2m.mon.mean.nc",plot=TRUE)
    [1] "Warning : Calendar attribute has not been found in the meta data"
    Error in R_nc_open: NetCDF: HDF error
    Error in open.ncdf(ncfile) : 
    Error in open.ncdf trying to open file /home/emcintir//tas_Amon_FIO-ESM_rcp45_000.nc
    In addition: Warning message:
    closing unused connection 3 (DSensemble.t2m-log.txt) 

Noting files are present:

    dir(path="~", pattern=".nc")
    [1] "air.2m.mon.mean.nc"              "tas_Amon_FIO-ESM_rcp45_000.nc"   "tas_Amon_NorESM1-M_rcp45_000.nc"

In any case, this is more of an issue with your example. The dataset is not included in your package, so the example can't work, *even if* I successfully get the file from the internet.

**Comment by abdelkaderm** [comment] 2015-10-20 07:29
Hi there, thank you for the details. I will do an extensive check on the example and come back to you soon.
Bests,

**Comment by abdelkaderm** [comment] 2015-10-22 14:10
Hi there, 
It took me sometime to discover that the problem comes from the 'ncdf' library which has some troubles with R 3.2.2, 64-bit, you can try to use 
```r
open.ncdf("~/air.2m.mon.mean.nc")
```
and you will notice that it will return the same error 
> Error in R_nc_open: NetCDF: Unknown file format
Error in open.ncdf("C:\\Users/abdelkaderm/Downloads/merra_t2m.nc") : 
  Error in open.ncdf trying to open file C:\Users/abdelkaderm/Downloads/merra_t2m.nc

However, I did not get any problem with ncdf4. So please, install "ncdf4" instead and let me know if you still get the same problem or not. But before, you need to detach("ncdf") that is loaded with the esd package.

**Comment by monamidutta** [comment] 2015-11-14 13:46
Hi
I just wanna ask is this problem fixed, because i am still getting the same error with ncep reanalysis nc files. i removed the ncdf package but esd in not working without ncdf, please note that ncdf4 is in my library in-spite esd is not using ncdf4.

**Comment by abdelkaderm** [comment] 2015-11-15 08:00
you can force retrieve to use ncdf4 like
'retrieve.default <- function(x,...) retrieve.ncdf4(x,...)'

**Comment by abdelkaderm** [comment] 2015-11-15 08:01
I will try to have a look again on this

**Comment by eliotmcintire** [comment] 2015-11-20 01:48
Still having problems even with the two suggested work arounds. It is quite strange because the package when loading won't load correctly unless the ncdf package is present (i.e., it is not enough to only have the ncdf4 package, just to do a `library(esd)`. Using the remap for the `retrieve.default` function as suggested allows R to get through the file problem, but then I get this:

    rcp4.5 <- DSensemble.t2m(Oslo,path='',rcp='',pattern = "tas_Amon_",biascorrect=TRUE, area.mean.expl=TRUE, predictor = "air.2m.mon.mean.nc",plot=TRUE)
    [1] "Warning : Calendar attribute has not been found in the meta data"
    Error in if (i > 0) { : missing value where TRUE/FALSE needed

**Comment by brasmus** [comment] 2016-01-11 12:40
We will try to sort this out by having two branches with esd here on github, one using ncdf and the other ncdf4. We'll close this issue when that is finished.

**Comment by brasmus** [comment] 2016-03-02 14:44
We now have two branches for esd, one for ncdf4 (default) and one for ncdf. I close this issue now since the last entry was in January 11, but please open it again if the problem is not fixed.

**Closed by brasmus** 2016-03-02 14:44 UTC
